### ISSUE TITLE
cell abundance quantile

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#148]
Hi, 
how to explain deconvolution results stored in adata.obsm 'means_cell_abundance_w_sf', 'q05_cell_abundance_w_sf', 'q95_cell_abundance_w_sf' ? In my opinion, the cell numbers should be constant in each spot, why cell2location give many different values(q05, q95, mean) ? which one should I use to plot ?

**Comment by vitkl** [comment]
Hi @wangjiawen2013 

Cell2location estimates the posterior distribution of cell abundance - rather than one value. This distribution represents the uncertainty in the numbers. You can interpret `q05`, which corresponds to 5% quantile of the posterior distribution, as a high-confidence cell abundance. In a quantitative benchmark, we saw that 5% quantile provides a slightly more accurate result.

If you would like to learn more about Bayesian statistics and posterior distributions I recommend looking into the Statistical Rethinking course and the book: https://www.youtube.com/watch?v=BYUykHScxj8&list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN&index=1.

**Comment by vitkl** [comment]
I am assuming that this is resolved.
