### ISSUE TITLE
reference model retraining

### ISSUE THREAD

**Issue by wangjiawen2013** [BayraktarLab/cell2location#218]
Hi, 
When I loaded the pre-trained model with the following code according to cell2location tutorial,
adata_file = f"{ref_run_name}/sc.h5ad"
adata_ref = sc.read_h5ad(adata_file)
mod = cell2location.models.RegressionModel.load(f"{ref_run_name}", adata_ref)
mod were started to re-trained at the same time ! How to load the pre-trained model without trainning it again ?

**Comment by vitkl** [comment]
Hi @wangjiawen2013 

Retraining should not be happening. It's normal to see a training progress bar on load because 1 training step needs to be done to properly load the model - however, that doesn't change results in any way.

If you have the issue as here https://github.com/BayraktarLab/cell2location/issues/185 you need to update cell2location and scvi-tools.

If this is something else, could you please post the screenshot of what you are seeing?

**Comment by vitkl** [comment]
I am assuming that the problem is resolved and closing the issue.
