### ISSUE TITLE
A question about batch effect

### ISSUE THREAD

**Issue by LiuJiamao521** [BayraktarLab/cell2location#390]
Dear developers,

I would like to ask whether I still need to perform the 'Estimation of reference cell type signatures (NB regression)' step if my single-cell data and spatial transcriptomics data are from the same tissue section, I mean I have many such tissues from different stages, and for each tissue, both single-cell and spatial measurements were taken.

Thank you for your help and support. I look forward to your response!

#### Single cell reference data: technology type (e.g. mix of 10X 3' and 5')

10X

#### Spatial data: number of locations numbers, technology type (e.g. Visium, ISS, Nanostring WTA)

stereo-seq

**Comment by vitkl** [comment]
Hi @LiuJiamao521 

You can do spatial mapping for each time point separately but we recommend analysing all sections/time points together because this helps cell2location distinguish technology effects from changes in the abundance of cell types with time points. If you would like to do spatial mapping for all time points simultaneously, you need to correct the differences between 10x reactions (sequencing depth, soup) - so you need to use the regression model.

**Comment by LiuJiamao521** [comment]
thanks! it helps a lot.

**Comment by LiuJiamao521** [comment]
> Hi @LiuJiamao521
> 
> You can do spatial mapping for each time point separately but we recommend analysing all sections/time points together because this helps cell2location distinguish technology effects from changes in the abundance of cell types with time points. If you would like to do spatial mapping for all time points simultaneously, you need to correct the differences between 10x reactions (sequencing depth, soup) - so you need to use the regression model.

thanks! it helps a lot.
