### ISSUE TITLE
cuDNN version on AWS instances [probably theano does not use the GPU]

### ISSUE THREAD

**Issue by romain-lopez** [BayraktarLab/cell2location#50]
I'm unsure how the dependencies work in Theano but it is really inconvenient that cell2location cannot be simply installed on some broadly available hardware. Not sure if this is because you pinned down a particular version of Theano for the software, or because Theano is less maintained than pytorch or tensorflow (is it?). I hope that the new implementation in scvi-tools will help avoid those issues :)

I simply run some custom code that calls cell2location

**Output of nvidia-smi:**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   50C    P0    70W / 149W |    842MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Output of nvcc:**

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

**Output of cell2location:**

```
### Summarising single cell clusters ###
### Creating model ### - time 0.04 min
### Analysis name: LocationModelLinearDependentW_1experiments_5clusters_1600locations_2000genes
### Training model ###
/home/ubuntu/anaconda3/envs/scVI/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is morerecent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
```

**Comment by vitkl** [comment]
Tbh, I always see that warning - it is generally not a problem with cude 10.2, but I have not tested with cuda 11.0 or 11.2.

With your data size, the analysis should take 2-3 minutes (maybe 2x more on K80), certainly not hours. Are you sure that theano is using the GPU? 
You need this line in your script/notebook before importing cell2location:
```
import os
# this line forces theano to use the GPU and should go before importing cell2location
os.environ["THEANO_FLAGS"] = 'device=cuda0,floatX=float32,force_device=True'
```

**Comment by vitkl** [comment]
Hi @romain-lopez 

We are finalising a major revision of cell2location including backend (scvi-tools & pyro) and user interface. Please have a look at the new installation instructions and a new tutorial. Switching to scvi-tools addresses the issue we are discussing here. 

Also, note that we have added a feature for estimating the expression of every gene in every cell type across locations. The approach we use is based on the conditional expected expression proposed in the RCTD paper (the exact equation is different because we account for additional factors). I would be quite interested in seeing how this compares to DestVI. You can find this analysis in the advanced section of the tutorial.

Would be also good to if you can share any thoughts or feedback on the new interface and tutorials in discussions: https://github.com/BayraktarLab/cell2location/discussions/65.

**Comment by vitkl** [comment]
@romain-lopez would be good if you use cell2location with scvi-tools interface and the conditional expected expression for the benchmarks that you perform in DestVI paper.

Cell2location with scvi-tools interface resolves this issue so I will close it.
