### ISSUE TITLE
PYMC3 has been renamed to PyMC

### ISSUE THREAD

**Issue by canyon289** [BayraktarLab/cell2location#75]
Hi,
PyMC3 has been renamed PyMC. If this affects you and you have questions, or you want someone to direct your rage at I'm available! Do let me know how i, or any of the PyMC devs can help.

Ravin

**Comment by vitkl** [comment]
Hi @canyon289 and @twiecki

Thank you for getting in touch. Good to be aware of this. The last time I tried there was no support for GPU training with Variational Inference - https://discourse.pymc.io/t/with-all-the-changes-what-are-the-options-for-advi-training-on-gpus/7918. Do you have an idea of when this will be addressed?

@twiecki citing your response below, I am wondering what kind of parametrization changes you have in mind. This [file](https://github.com/BayraktarLab/cell2location/blob/master/cell2location/models/pymc3/LocationModelLinearDependentWMultiExperimentLocationBackgroundNormGeneAlpha.py) defines the model. My understanding is that the GPU is needed because of data size.
> Usually slow models can be sped up a lot by better parameterization.
