### ISSUE TITLE
In plot_genes_per_cell_type 

### ISSUE THREAD

**Issue by cveraszto** [BayraktarLab/cell2location#87]
In [tutorial_utils.py ](https://github.com/BayraktarLab/cell2location/blob/master/docs/notebooks/tutorial_utils.py)
`slide.uns["mod"]["factor_names"]` is hardcoded but some slides instead have `slide.uns["mod"]["fact_names"]`

**Comment by vitkl** [comment]
@cveraszto Thanks for using cell2location and looking into per cell type expression analysis. I would be curious to see what you learn with this approach and where you take it because it is quite experimental.

Re your issue. In august, we have completely changed the backend of cell2location (from pymc3 to pyro&scvi-tools). Please use this new version which is more accurate and numerically robust (simply install cell2location again as explained in readme). The new version should not have `slide.uns["mod"]["fact_names"]`.

Also, we did not make this function part of the package because there will often be a need to modify it depending on the dataset. You can copy it your folder and modify as necessary.

**Comment by cveraszto** [comment]
Will do! 
I believe the `quay.io/vitkl/cell2location:latest` docker image still contains the old version, maybe that is why I got confused. I remember you told me you don’t use docker yourself though.

**Comment by vitkl** [comment]
We will make a new docker version soon, we are waiting until we find and
correct as many issues with the new version as possible. Should be soon.
