### ISSUE TITLE
Question: Extract cell type contribution per spot 

### ISSUE THREAD

**Issue by ccruizm** [BayraktarLab/cell2location#88]
Good day,

I would like to extract and export (csv) the deconvoluted cell proportions of each spot to visualize it in a scatter pie chart. 

I was planning on using the `q05_cell_abundance_w_sf` matrix. However, I am not sure how I can transform the values of each cell abundance into a proportion, since each spot will have a different enrichment value per predicted cell type. 

Could you guide me on how I can do that, please? 

Thanks in advance!

**Comment by vitkl** [comment]
Hi Cristian

See Cell 16 in our main tutorial:
https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html#Visualising-cell-abundance-in-spatial-coordinates

You can save that as a CSV:
```python
adata_vis.obsm['q05_cell_abundance_w_sf'].to_csv('q05_cell_abundance_w_sf.csv')
```
It is generally best practice to avoid using pie charts because human are
much worse at assessing angles than distances or colour intensities. There
are other ways to summarize and present this data - some of which are shown
in the same tutorial. You can also show the abundance of cell types in
histologically defined tissue regions (as a dot plot of average abundance,
where regions are annotated in 10X Loupe browser).

**Comment by ccruizm** [comment]
Thank you very much! will follow your advice
